version: "3.7"

services:
  app:
    image: existenz/webstack:8.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project-1.rule=Host(`project-1.local`)"
      - "traefik.http.routers.project-1.entrypoints=web"
      - "traefik.http.services.project-1.loadbalancer.server.port=80"
    volumes:
      - ./src:/www/public
